services:
  - type: web
    name: quinta-ypua-angular
    plan: free
    runtime: node
    region: frankfurt
    branch: main

    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/pousada-app

    envVars:
      - key: NODE_VERSION
        value: 20
