services:
  - type: web
    name: quinta-ypua-angular
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/pousada-app
    pullRequestPreviewsEnabled: true

    routes:
      - type: rewrite
        source: /*
        destination: /index.html
